version: 2

jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: Installing sudo
          command: |
            apt-get update
            apt-get install -y sudo
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Installing Build System
          command: |
            apt-get update
            apt-get install -y git build-essential libboost-system-dev cmake python2.7
            apt-get install -y curl cpio
            apt-get install -y libcairo2-dev
            apt-get install -y libjpeg-turbo8-dev libjpeg8-dev libwebp-dev libglvnd-dev

      - checkout
      - run:
          name: Setup 3rd Party Modules
          command: |
            git submodule sync
            git submodule update --init
            cd svg-native-viewer
            git submodule sync
            git submodule update --init
            cd third_party
            curl https://home.hiroshima-u.ac.jp/mpsuzuki/skia-m70_ubuntu1804_20190517.cpio.xz | xz -cd | cpio -vidum

      - run:
          name: Creating Build Files
          command: |
            cd svg-native-viewer/svgnative
            cmake -Bbuild/linux -H. -DSTYLE=ON -DSKIA=ON -DCAIRO=ON

      - run:
          name: Creating Binary Files
          command: |
            cd svg-native-viewer/svgnative
            make -C build/linux

      - run:
          name: Run tests
          command: |
            cd svg-native-viewer/svgnative
            /usr/bin/python2.7 script/runTest.py --test=test
